language: python
python:
  - "2.7"
install:
  - make deps
script:
  - make test_xunit
  - make lint
  - make docker_build
  - make docker_push
services:
  - docker
after_success:
  - make docker_push
deploy:
  provider: heroku
  app: whispering-meadow-93101
  api_key: ${HEROKU_API_KEY}
